sudo: false
language: python
python:
  - '3.4'
install: "./etc/install.sh"
script: "./etc/build.sh"
env:
  global:
    secure: "Ggyj5gOT1+v//VdSS3ffXU3HKqdcQqXRqaoq8xRm0tFuBIXqNyztLVP31Z4Hp3bieSgyYksc0PRQnIWVPDJhcrARhvKBDNNadchEsFfrOGbBnDN0SmYA4GJfdWqv5mwzhFULo8nC2XbmTpgutBfHz3dUtcRzy+/UQuYec9tOK/BO4uAijFAgm20sqBL/OvdV29OvHylTp4KMp+0MsIsRJKlA5xsOhMwhXHpDhcEmylRUX/FCFNgv7783FEYLBcIK/ODAv5oddky+T6iKRbEmgoSV04+Xh7cY/WiwJR8cl6o2F3H3QoX1txYfXLiVEw2KS7T1hvVOPVI2mqhhzOQqnHc1ttqqzoFaPzHUjHGIn2F/OIs4+ArX1C4I2YqWo+6wnfT2fpeJaxGWhUaFKjrLC5o5kX1t0FDX5gyyxoTnvMEDdsIXSMczsAXtCJC2TfwcWjkQNJprOJJC+F3vM4TOKxNoVfZGtJkuxlAmAs6zbxzk9dE8Ace6U2ECIvh7iMJvQqsWDkYDzritVD0KuEkLbEzwhCmoCxcCVKfJSyD5KGa2PIdB3Bgia3kqlYos0qSa355DT6Cs6Mo8oMt0/wiHk/L27NGlHQESE5VbNBh9EL3k68iRgyrZ84n7uqsuW6sjyABL5Hh0HGQsjz8k1s9sHr9ol6SRXkjCQqm0FVIrjeo="
notifications:
  email: false
